<div data-bind="scope: 'base-layout'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "base-layout": {
                        "component": "Study_KO/js/view/default-layout",
                        "children" :{
                            "buttonShowCurrentDate": {
                                "component" : "Study_KO/js/action/button-show-date",
                                "displayArea": "buttonShowDate",
                                "children" : {
                                    "changeCurrentDateColor": {
                                        "component": "Study_KO/js/action/change-date-color",
                                        "displayArea": "changeDateColor"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
</script>